name: rental_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.10.0
  firebase_app_check: ^0.2.0+0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.5.0
  image_picker: ^0.8.7+5
  url_launcher: ^6.1.10
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  flutter_local_notifications: ^17.1.2
  share_plus: ^7.2.1
  firebase_messaging: ^14.6.0
  google_sign_in: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"